global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['discovery-service:8761']

  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:9090']

  - job_name: 'elastic-query-service'
    metrics_path: '/elastic-query-service/actuator/prometheus'
    static_configs:
      - targets: ['elastic-query-service:8183']

  - job_name: 'elastic-query-web-client'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['elastic-query-web-client:8184']

  - job_name: 'kafka-streams-service'
    metrics_path: '/kafka-streams-service/actuator/prometheus'
    static_configs:
      - targets: ['kafka-streams-service:8187']

  - job_name: 'kafka-to-elastic-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['kafka-to-elastic-service:8188']
